### ISSUE TITLE
Reimplement file views in smtweb as classes

### ISSUE THREAD

**Issue by apdavison** [open-research/sumatra#136]
The `show_file()` function in `sumatra.web.views` has a long `if ... elif ... elif ... elif` block handling different mimetypes.

If each of the sub-blocks were replaced by a class, it would make it easier for users to customize this.

Depends on the planned plugin system.

 _Imported from Bitbucket issue [132](https://bitbucket.org/apdavison/sumatra/issue/132),  created by apdavison on 02-18-2013 at 13:17, last modified: 05-15-2013 at 11:26_

**Comment by babsey** [comment]
I am not able to find this function `show_file()` in `sumatra.web.views`. I think this issue is deprecated.
