### ISSUE TITLE
Drop dependency on simplejson

### ISSUE THREAD

**Issue by apdavison** [open-research/sumatra#190]
Now that sumatra requires Python2.6+, the stdlib json should be enough(?), rather than having a dependency on simplejson.
        

 _Imported from Bitbucket issue [204](https://bitbucket.org/apdavison/sumatra/issue/204),  created by anntzer on 04-23-2014 at 06:27, last modified: 04-27-2014 at 19:32_

**Comment by apdavison** [comment]
I agree. It should be straightforward to get rid of the simplejson requirement.
        

_Trac comment by apdavison on 04-25-2014 at 22:21_

**Comment by maxalbert** [comment]
This was fixed in commit 902e102bcc295f209fdb.
