### ISSUE TITLE
Parameters on the command line are (silently) ignored after Sumatra upgrade

### ISSUE THREAD

**Issue by apdavison** [open-research/sumatra#193]
This is a bug report on behalf of another user who experienced the following issue:

After upgrading Sumatra to version 0.6.0 any parameters supplied on the command line would be ignored. There was no error message, but Sumatra would just silently use the values in the `default.param` file.

After some debugging the reason seems to be that the option `allow_command_line_parameters` in the file `.smt/project` was set to `null`. Instead, it should have been set to `true` because the project was never configured with the `--plain` option. I presume that this happened during the upgrade because the option was only introduced recently?

I'm currently travelling so can't reproduce this on my own or look into it for another week, but I wanted to report it because it seems like a dangerous and annoying issue (dangerous because a user might not notice it for a long while because there is no error message and annoying because it's not clear how to change it from a user's point of view). I also thought that there is probably a quick fix, but otherwise I'm happy to dig into it once I'm back.
        

 _Imported from Bitbucket issue [207](https://bitbucket.org/apdavison/sumatra/issue/207),  created by cilix on 05-02-2014 at 12:06, last modified: 05-05-2014 at 20:21_

**Comment by maxalbert** [comment]
This was fixed in commit `46d05a388eb81614`.
