### ISSUE TITLE
smt list --long fails with non-ASCII username

### ISSUE THREAD

**Issue by timtroendle** [open-research/sumatra#213]
Having a non-ASCII character in my name, ``smt list --long`` fails with an ``UnicodeEncodingError``. ``smtweb`` is not affected. 

     UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 6: ordinal not in range(128)

This happens in line 68 of ``sumatra/formatting/__init__.py`` in version 0.6.0. Checking the code, I assume this'll happen for any other record entry as well.

This bug is similar but not identical to #172.

**Comment by timtroendle** [comment]
This is solved with #242.

**Comment by apdavison** [comment]
We should probably have a unit test for this, to avoid regressions.

**Comment by apdavison** [comment]
Added unit test in ec63af1

**Comment by timtroendle** [comment]
I also added a unittest, but in a slightly different way ([branch in my fork](https://github.com/timtroendle/sumatra/tree/enhancement/unicode-in-records)) which led me to the following issue: ``open`` can fail with unicode as the encoding chosen is platform dependent (based on the ``locale`` module). That is especially a problem on Windows where ``UTF-8`` is not the default.

One solution is to always specify the encoding explicitely, as discussed [on the Python-Dev mailing list](http://www.gossamer-threads.com/lists/python/dev/928025) and [by python-future](http://python-future.org/compatible_idioms.html#file-io-with-open). Maybe it's not necessary to change that here, but probably still worthwhile to keep in mind.

**Comment by apdavison** [comment]
Agreed. I don't currently test on Windows, although I've just registered with Appveyor; it just needs someone to write the appveyor.yml file.
