### ISSUE TITLE
when storing record after fresh install: AttributeError: 'module' object has no attribute 'db' 

### ISSUE THREAD

**Issue by wwwwwwwwwwwwwwwwwwwwwwwww** [open-research/sumatra#217]
#####################################################################
bkw@Limette-U64:~/code/teachtool$ sudo pip install django --upgrade
Requirement already up-to-date: django in /usr/local/lib/python2.7/dist-packages
Cleaning up...

bkw@Limette-U64:~/code/teachtool$ sudo pip install sumatra --upgrade
Requirement already up-to-date: sumatra in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: Django>=1.4 in /usr/local/lib/python2.7/dist-packages (from sumatra)
Requirement already up-to-date: django-tagging in /usr/local/lib/python2.7/dist-packages (from sumatra)
Downloading/unpacking httplib2 from https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.tar.gz#md5=09d8e8016911fc40e2e4c58f1aa3ec24 (from sumatra)
  Downloading httplib2-0.9.tar.gz (204kB): 204kB downloaded
  Running setup.py (path:/tmp/pip_build_root/httplib2/setup.py) egg_info for package httplib2
    
Downloading/unpacking simplejson from https://pypi.python.org/packages/source/s/simplejson/simplejson-3.6.5.tar.gz#md5=b65dc21c7aaad14c6b4ad0d9179e437d (from sumatra)
  Downloading simplejson-3.6.5.tar.gz (73kB): 73kB downloaded
  Running setup.py (path:/tmp/pip_build_root/simplejson/setup.py) egg_info for package simplejson
    
Requirement already up-to-date: docutils in /usr/local/lib/python2.7/dist-packages (from sumatra)
Downloading/unpacking jinja2 from https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.tar.gz#md5=b9dffd2f3b43d673802fe857c8445b1a (from sumatra)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py (path:/tmp/pip_build_root/jinja2/setup.py) egg_info for package jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Requirement already up-to-date: parameters in /usr/local/lib/python2.7/dist-packages (from sumatra)
Downloading/unpacking markupsafe from https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e (from jinja2->sumatra)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_root/markupsafe/setup.py) egg_info for package markupsafe
    
Installing collected packages: httplib2, simplejson, jinja2, markupsafe
  Found existing installation: httplib2 0.8
    Uninstalling httplib2:
      Successfully uninstalled httplib2
  Running setup.py install for httplib2
    
  Found existing installation: simplejson 3.3.1
    Uninstalling simplejson:
      Successfully uninstalled simplejson
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/simplejson/_speedups.o -o build/lib.linux-x86_64-2.7/simplejson/_speedups.so
    
  Found existing installation: Jinja2 2.7.2
    Uninstalling Jinja2:
      Successfully uninstalled Jinja2
  Running setup.py install for jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Found existing installation: MarkupSafe 0.18
    Uninstalling MarkupSafe:
      Successfully uninstalled MarkupSafe
  Running setup.py install for markupsafe
    
    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/markupsafe/_speedups.o -o build/lib.linux-x86_64-2.7/markupsafe/_speedups.so
Successfully installed httplib2 simplejson jinja2 markupsafe
Cleaning up...

bkw@Limette-U64:~/code/teachtool$ smt init teachtool
Sumatra project successfully set up

bkw@Limette-U64:~/code/teachtool$ smt configure -cstore-diff

bkw@Limette-U64:~/code/teachtool$ smt run --executable=python --main=src/test_svm.py
Using /usr/bin/python
!!!!! modified set(['src/test_svm.py'])
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  import gobject._gobject
opencv version: 2.4.9
number of features for each sample: 200
sample count 3005
Record label for this run: '20150329-123641'
No data produced.
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/sumatra/commands.py", line 370, in run
    version=args.version or 'current')
  File "/usr/local/lib/python2.7/dist-packages/sumatra/projects.py", line 200, in launch
    self.add_record(record)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/projects.py", line 242, in add_record
    except (django.db.utils.DatabaseError, sqlite3.OperationalError):
AttributeError: 'module' object has no attribute 'db'
bkw@Limette-U64:~/code/teachtool$ 
#################################################################

.smt folder contains only one file: project:
{
  "default_executable": null, 
  "default_repository": {
    "url": "/home/bkw/code/teachtool", 
    "type": "sumatra.versioncontrol._mercurial.MercurialRepository", 
    "upstream": "http://laotse:8080/scm/hg/projects/teachtool"
  }, 
  "name": "teachtool", 
  "input_datastore": {
    "root": "/", 
    "type": "sumatra.datastore.filesystem.FileSystemDataStore"
  }, 
  "default_launch_mode": {
    "working_directory": "/home/bkw/code/teachtool", 
    "type": "sumatra.launch.SerialLaunchMode", 
    "options": null
  }, 
  "record_store": {
    "db_file": "/home/bkw/code/teachtool/.smt/records", 
    "type": "sumatra.recordstore.django_store.DjangoRecordStore"
  }, 
  "data_store": {
    "root": "/home/bkw/code/teachtool/Data", 
    "type": "sumatra.datastore.filesystem.FileSystemDataStore"
  }, 
  "on_changed": "store-diff", 
  "data_label": null, 
  "default_main_file": null, 
  "label_generator": "timestamp", 
  "_most_recent": null, 
  "sumatra_version": "0.6.0", 
  "allow_command_line_parameters": true, 
  "timestamp_format": "%Y%m%d-%H%M%S", 
  "description": ""
}

**Comment by wwwwwwwwwwwwwwwwwwwwwwwww** [comment]
solution suggested on https://groups.google.com/forum/#!topic/sumatra-users/xJpkNv8BBXA resolved problem: downgrade django to 1.5 (sumatra seems not to be compatible with django 1.7.6 and 1.7.7 (both tested by me))

**Comment by maxalbert** [comment]
Glad to hear downgrading django solved it. This probably isn't relevant for you at the moment, but for the record (or in case someone else stumbles upon this issue): the current development version of Sumatra (0.7dev) requires django 1.6. I don't know what the plans are for upgrading to a more recent version of django (or how easy/difficult it would be).
