### ISSUE TITLE
add bash completion for smt

### ISSUE THREAD

**Issue by ashander** [open-research/sumatra#224]
Especially when default labels are assigned, using `smt` commands that take labels as positional arguments is onerous.

The [argcomplete module](https://github.com/kislyuk/argcomplete) seems like it would make this straightforward to add.

**Comment by apdavison** [comment]
Nice idea.

**Comment by ashander** [comment]
As a more large-scale issue, interfacing subcommand and options with bash completion would be greatly facilitated by migrating _all_ the parsing to a library.

Currently the top-level parsing just uses `sys.argv` then dispatches to subcommands which each have their own parser constructed with `argparse`. Although argparse has great aspects, I believe it's a bit tough to build a subcommmand-driven parser with it (thus the current construction I guess).
 
There are some great-seeming, recently-developed tools capable of implementing a complex CLI like `smt`. One example is cliff, but [click](https://github.com/mitsuhiko/click) seems more well-supported and documented. (See `repo` example for a subcommand system.) 

Moving to one of these would not only support completion, but could aid long term maintenance and extensibility. For example, at the cost of some UI rigidity, it will make the CLI a little more self-documenting (removing the need for maintaining `bin/smt` by using entry points and providing top-level options for the `smt` command. Additionally, click in particular is python 2/3 agnostic so could help ease that transition (though of course the CLI is a very small part of this issue).

**Comment by apdavison** [comment]
+1 for migrating command-line parsing to a more modern library. Can you create a new ticket for this?

**Comment by ashander** [comment]
Done. And closing this for now. PR #230 is a rough implementation with current codebase. Longer term migration #234 will have to deal with this in context
