### ISSUE TITLE
pull request review checklist

### ISSUE THREAD

**Issue by ashander** [open-research/sumatra#235]
Does this project have a policy for what to review in a PR? If there's a checklist somewhere, it could be useful in aiding non-core contributors (like me) in reviewing.

For example @apdavison recently pushed PR #232 and #233 , if I want to be helpful in reviewing either of those I'm not sure of the criteria.

**Comment by apdavison** [comment]
We don't have a checklist at present, but this is a very good idea.

**Comment by apdavison** [comment]
I just created a pull request for this: #239
