### ISSUE TITLE
OSError: File name too long for parameter file content

### ISSUE THREAD

**Issue by babsey** [open-research/sumatra#259]
Hello,

I started Sumatra 2 months ago so I am newbie in that program. It might be only my mistake.
When I have long content in parameter file (8 lines or over 300 characters) and I am not able to get 
this record.parameter.to_sumatra() without error. By the way I use simple parameter set.

The content of the error displayed when I want go to Record detail on website: [Errno 36] File name too long: 'content of parameter file'.

I want ask you if anyone also gets this type of error.

Thanks in advance,
Sebastian

**Comment by timtroendle** [comment]
I can reproduce that with the most recent sumatra version 0.7.0rc1. I fixed it for that version. Just to be sure, is that the version you are using?

**Comment by babsey** [comment]
yes, I used the newest version of open-research/sumatra (92d9dbe).

**Comment by maxalbert** [comment]
@babsey This should be fixed with the merge of @timtroendle's fix in #260. If you have a chance it would be great if you could confirm whether it works now.

**Comment by babsey** [comment]
I checked and it works well.
