### ISSUE TITLE
Using @capture decorator makes python "print" unusable.

### ISSUE THREAD

**Issue by anandtrex** [open-research/sumatra#268]
Using instructions from [the sumatra documentation](https://pythonhosted.org/Sumatra/using_the_api.html) I've used 'capture' decorator in my code. But after I do this, I'm unable to print any string whatsoever using the print statement. I get an exception that reads "TypeError: unicode argument expected, got 'str'"

This code snipped reproduces the issue:
```
# test.py
import sys
from sumatra.parameters import build_parameters
from sumatra.decorators import capture

@capture
def main(parameters):
    print "Hi"

parameter_file = sys.argv[1]
parameters = build_parameters(parameter_file)
main(parameters)
```
```
# params.yaml
---
testing: 10
```

On the commandline, I run:
```
python test.py params.yaml
```

I'm running python 2.7.9 and Sumatra 0.7.0rc1 (installed from PyPi)

**Comment by timtroendle** [comment]
I can reproduce that. ``print`` seems to always write ``str`` into stdout in Python2; while the function grabbing the stdout expects ``unicode``. I assume a StreamWriter converting ``str`` to ``unicode`` -- similar to ``codecs.getwriter('utf-8')`` -- should solve that issue. Need to take a closer look again.

**Comment by anandtrex** [comment]
One note I'd like to add is that print works fine outside the decorated function, both before and after it is called. It is only somehow modified by the decorator.

**Comment by timtroendle** [comment]
I made a change to the decorator that should solve this. If you can try it.

**Comment by anandtrex** [comment]
Yeah, I can confirm that that fixes the issue. Thanks!

**Comment by apdavison** [comment]
This is now in the 0.7.2. release.
