### ISSUE TITLE
Timestamp based approach for finding generated project files

### ISSUE THREAD

**Issue by anandtrex** [open-research/sumatra#272]
I ran into the issue of having to run multiple experiments simultaneously and having them recorded in sumatra. As documented in `sumatra/datastore/filesystem.py::_find_new_data_files` this approach requires different roots for each run, which breaks the workflow of sumatra.

I made some small changes (output of git diff with current master below) which allows me to pass in the output directory for each specific run to sumatra, so sumatra looks only within that directory. Right now, this is useful only when using the sumatra API from within a script following [instructions here](https://pythonhosted.org/Sumatra/using_the_api.html).

I'm not sure if this would be useful for other users, but if so, I'd be willing to extend it to make it generally applicable. (I can submit it as a pull request if desired).

```
diff --git a/sumatra/datastore/filesystem.py b/sumatra/datastore/filesystem.py
index 2434b79..ef732ee 100644
--- a/sumatra/datastore/filesystem.py
+++ b/sumatra/datastore/filesystem.py
@@ -97,7 +97,7 @@ class FileSystemDataStore(DataStore):
                 pass  # should perhaps emit warning
     root = property(fget=__get_root, fset=__set_root)

-    def _find_new_data_files(self, timestamp, ignoredirs=[".smt", ".hg", ".svn", ".git", ".bzr"]):
+    def _find_new_data_files(self, timestamp, out_dir, ignoredirs=[".smt", ".hg", ".svn", ".git", ".bzr"]):
         """Finds newly created/changed files in dataroot."""
         # The timestamp-based approach creates problems when running several
         # experiments at once, since datafiles created by other experiments may
@@ -106,9 +106,14 @@ class FileSystemDataStore(DataStore):
         # their own datastore, each with a different root.
         timestamp = timestamp.replace(microsecond=0)  # Round down to the nearest second
         # Find and add new data files
-        length_dataroot = len(self.root) + len(os.path.sep)
         new_files = []
-        for root, dirs, files in os.walk(self.root):
+        if out_dir:
+            path = out_dir
+        else:
+            path = self.root
+        length_dataroot = len(self.root) + len(os.path.sep)
+
+        for root, dirs, files in os.walk(path):
             for igdir in ignoredirs:
                 if igdir in dirs:
                     dirs.remove(igdir)
@@ -120,10 +125,10 @@ class FileSystemDataStore(DataStore):
                     new_files.append(relative_path)
         return new_files

-    def find_new_data(self, timestamp):
+    def find_new_data(self, timestamp, out_dir=None):
         """Finds newly created/changed data items"""
-        return [DataFile(path, self).generate_key()
-                for path in self._find_new_data_files(timestamp)]
+        return [DataFile(path, self, out_dir=out_dir).generate_key()
+                for path in self._find_new_data_files(timestamp, out_dir)]

     def get_data_item(self, key):
         """
```

**Comment by apdavison** [comment]
What is the problem with changing the DataStore root for each run? How does it break the workflow?

There is the solution outlined at http://sumatra.readthedocs.org/en/latest/faq.html#when-i-run-more-than-one-simulation-at-once-sumatra-mixes-up-the-output-files-how-can-i-make-it-associate-the-right-files-with-the-right-simulation and it works fine for me.

**Comment by anandtrex** [comment]
Ok, I assumed "changing the Datastore root" meant changing the root of the project itself. The one outlined in your link makes sense and would work. Maybe a section in the main documentation page on working with multiple runs would make this more visible?

**Comment by apdavison** [comment]
As well as the FAQ, this approach is documented [here](http://sumatra.readthedocs.io/en/latest/handling_data.html#running-multiple-computations-at-the-same-time), and there is a link to the relevant section of the FAQ in [this sub-section](http://sumatra.readthedocs.io/en/latest/managing_a_project.html#handling-input-and-output-data)

I'm going to close this ticket now, but I'm happy to receive pull requests for documentation changes that would make this clearer.
