### ISSUE TITLE
Download button does not download file

### ISSUE THREAD

**Issue by timtroendle** [open-research/sumatra#274]
Simply put, when pressing the download button in a data detail view of ``smtweb``, the file does not get downloaded but rendered in browser. Linebreaks in text files are not displayed, so the file is difficult to read and can't be copied manually either. Trying to render binary files obviously doesn't make sense at all.

sumatra: 0.7.2
DataStore: FileSystemDataStore
Browser: Firefox, Internet Explorer

**Comment by apdavison** [comment]
PR #284 attempts to fix this, to the extent that it can be fixed (Safari still displays text files in the browser, since it does not support the HTML5 "download" attribute of the `<a>` tag, but binary files should be correctly downloaded).

**Comment by timtroendle** [comment]
Yes, that seems to solve the problem in Firefox, thanks!

**Comment by apdavison** [comment]
Fixed in 0.7.3 release
