### ISSUE TITLE
dependencies in Sumatra v0.6

### ISSUE THREAD

**Issue by babsey** [open-research/sumatra#277]
Hello,

I have a project which ran with Sumatra v0.6 and is not able to upgrade to Sumatra v0.7. 
But I use virtualenv for Sumatra v0.6 and found out that some packages is not compatible to this Sumatra version. 

It works with Sumatra v0.6 (especially Django and django-tagging)
Django (1.6.11)
django-tagging (0.3.1)
docutils (0.12)
gitdb (0.6.4)
GitPython (1.0.1)
httplib2 (0.9.1)
Jinja2 (2.8)
parameters (0.2.1)
simplejson (3.8.0)

Should these dependencies implemented in Sumatra v0.6?
e.g. django >=1.4 <= 1.6.11
or django-tagging <= 0.3.1

Best,

**Comment by apdavison** [comment]
Why can't you upgrade to Sumatra v0.7?

**Comment by babsey** [comment]
I found out what the problem was. I use the relative path in project file and sumatra v0.6 only works with absolute path when I want to export the project and record file for upgrade.

By the way, should the dependency problem be ignored because the version is outdated?

**Comment by apdavison** [comment]
I don't plan to make any more 0.6.x releases. I'd rather put effort into ensuring all 0.6 projects can be upgraded to 0.7.
