### ISSUE TITLE
smt configure --mirror has no effect 

### ISSUE THREAD

**Issue by livia-b** [open-research/sumatra#281]
The mirror option is handled in init() https://github.com/open-research/sumatra/blob/master/sumatra/commands.py#L117 but not in configure https://github.com/open-research/sumatra/blob/master/sumatra/commands.py#L240

**Comment by apdavison** [comment]
Fixed in master and the 0.7 branch. I plan to make a bug-fix release in the next couple of days.

**Comment by apdavison** [comment]
Fixed in 0.7.3 release
