### ISSUE TITLE
MIME type detection appears to be broken

### ISSUE THREAD

**Issue by richardotis** [open-research/sumatra#307]
CSV files in the output do not have an associated MIME type reported (says "unknown") and consequently don't render in the detail view. If I manually modify the `metadata` dictionary in the relevant `DataKey` of `output_files` to set an explicit `mimetype` value, it will work.

**Comment by apdavison** [comment]
This should now be fixed in the current master branch (commit 379839447d62ce7724bd4de8cecc764bcd7a773e). Can you install from master and let me know if this fixes the problem for you?

**Comment by richardotis** [comment]
I probably won't have time to check this quickly because my project has taken me away from the Sumatra-facing components (for now). If CSV files are getting read with the right `mimetype` attribute now you can consider the matter resolved for me. I think my workaround is forward-compatible anyway so I'm okay either way.
