### ISSUE TITLE
Setting addlabel to None from command line

### ISSUE THREAD

**Issue by adamist521** [open-research/sumatra#316]
`smt configure -l cmdline` or `smt configure -l timestamp` works but `smt configure -l None` does not work.
I couldn't figure out a way to set `--addlabel` option to `None`.
Is it on somewhere? Did I miss it?

**Comment by apdavison** [comment]
You didn't miss it. This is a bug. There is a fix in pull request #318.

As a workaround until the PR is reviewed, you could manually edit `.smt/project` and change `"data_label"` to `null`
