### ISSUE TITLE
Errors when running unittests

### ISSUE THREAD

**Issue by GregorWautischer** [open-research/sumatra#339]
Got sumatra by following the instruction from the Developers' guide. Running nosetests finished failed with 21 errors. Errors come from test_recordstore.py, test_versioncontrol.out and test_web.out. the outputs from the individual tests running nosetests --with-coverage --cover-erase --cover-package=sumatra --cover.html test_xxxx.py are enclosed. Running on Ubuntu 14.04 on a virtual environment. The output of pip list is enclosed as well.

Thanks for help
[output.zip](https://github.com/open-research/sumatra/files/208499/output.zip)

**Comment by apdavison** [comment]
It looks as though the `mercurial` package is missing (`hg_api` is a wrapper around the command-line `hg` command).

I've updated the Developers' guide. You should either globally install [Mercurial](https://www.mercurial-scm.org) on your system, or run `pip install mercurial` in your virtualenv.
