### ISSUE TITLE
ImportError: No module named configparser in Sumatra 0.7.4 (0.7.3 works fine)

### ISSUE THREAD

**Issue by kierson** [open-research/sumatra#352]
Python: 2.7.13
Sumatra: 0.7.4

Problem:
Can't use any of the Sumatra commands (even smt --version) because of the following error
```
ImportError: No module named configparser
```

installing Sumatra `0.7.3` via pip fixed the problem.

**Comment by tgpfeiffer** [comment]
See http://python-future.org/whatsnew.html#what-s-new-in-version-0-16-0-2016-10-27

> This release removes the configparser package as an alias for ConfigParser on Py2 to improve compatibility with Lukasz Langa’s backported configparser package. Previously python-future and the configparser backport clashed, causing various compatibility issues. (Issues #118, #181)
>
> If your code previously relied on configparser being supplied by python-future, the recommended upgrade path is to run pip install configparser or add configparser to your requirements.txt file.

I suggest to add the `configparser` package as a dependency.

**Comment by kierson** [comment]
Correct me if I am wrong but I think it won't help as you rely on `import configparser ...` in the Sumatra's code which will work only for Python 3. In Python 2 it should use `import ConfigParser ...`.
I already tried installing `configparser` manually and it didn't help.

I had to go back to Sumatra `0.7.3`

**Comment by tgpfeiffer** [comment]
It worked for me:

```
$ pip install sumatra==0.7.4 configparser
...
Successfully installed Django-1.8.17 MarkupSafe-0.23 configparser-3.5.0 django-tagging-0.4.5 docutils-0.13.1 future-0.16.0 httplib2-0.10.3 jinja2-2.9.5 parameters-0.2.1 pathlib-1.0.1 sumatra-0.7.4
$ smt
Usage: smt <subcommand> [options] [args]

Simulation/analysis management tool version 0.7.4
...
```

**Comment by timtroendle** [comment]
Could reproduce the issue and @tgpfeiffer's fix and updated the dependencies accordingly in #353.
