### ISSUE TITLE
What is the syntax for adding user-defined keyboard shortcut to trigger external viewers?

### ISSUE THREAD

**Issue by llinfeng** [open-research/sumatra#355]
## User case:

According to the documentation for the Advanced setting, as of: http://www.sumatrapdfreader.org/settings3.1.html, the following settings are opening up my external editors fluently. The file in the Sumatra session should also be automatically loaded in the new "Viewer" session. Nice job!
```

ExternalViewers [
	[
		CommandLine = "c:\Program Files (x86)\ABBYY FineReader 12\FineReader.exe"
		Name = "ABBYY"
	]
	[
		CommandLine = "C:\Program Files (x86)\Adobe\Acrobat 11.0\Acrobat\Acrobat.exe"
		Name = "Adobe"
	]
]

```

## More over: menu shortcut are possible through `&`
Doing the following small adjustment to the `Name` shall create a "Menu-shortcut", where ABBYY could not be triggered through pressing `Y` when I have activated the File menu-item.

* The setting: `Name = "ABBY&Y"` ==> Featuring the magical `&`!
* The outcome:
![goodmenushortcut](https://cloud.githubusercontent.com/assets/5890407/24884685/96319f9c-1e18-11e7-93ae-ecc694d06967.png)

## Request: how to trigger these External Viewers through REAL Shortcuts?
I would like to trigger these external Viewers through a keyboard shortcut, especially for the ABBYY Findreader. (This software is reasonably good at OCR, but really lacks command-line support. So, the best way I can think of is to implement a shortcut for triggering it as an external viewer through  Sumatra.

### External pointer
I have asked the same question in another Sumatra repo, as: https://github.com/sumatrapdfreader/sumatrapdf/issues/777

**Comment by apdavison** [comment]
This is a different project named Sumatra; it is not Sumatra PDF reader
