### ISSUE TITLE
Wrong license on the website

### ISSUE THREAD

**Issue by lahwaacz** [open-research/sumatra#377]
[Your website](http://neuralensemble.org/sumatra/) says "Licence: CeCILL" but the [LICENSE file](https://github.com/open-research/sumatra/blob/master/LICENSE) contains a BSD license.

**Comment by apdavison** [comment]
Many thanks for spotting that. The project was relicenced sometime ago, but I forgot to change the entry on neuralensemble.org. Now fixed.
