### ISSUE TITLE
Outputs and labels mismatch when jobs are launched in batch

### ISSUE THREAD

**Issue by kailaix** [open-research/sumatra#390]
When multiple jobs are launched at the same time using `smt run -l <label> ... &`, despite that `<label>` are different, all generated data files and plots are shown in only one label.  I guess maybe it is because Sumatra tracks the generated files using the lasted launched job. Any idea of how to align the outputs and labels?

**Comment by apdavison** [comment]
Hi @kailaix - it's in the FAQs:

https://sumatra.readthedocs.io/en/latest/faq.html#when-i-run-more-than-one-simulation-at-once-sumatra-mixes-up-the-output-files-how-can-i-make-it-associate-the-right-files-with-the-right-simulation

**Comment by kailaix** [comment]
Thanks. That helps!
